[package]
name = "shell-command"
version = "0.0.0"
authors = [ "Ice <icegriffin1122@gmail.com>",]
edition = "2018"
publish = false

[lib]
path = "src/adder.rs"

[dependencies.elrond-wasm]
version = "0.29.3"

[dev-dependencies.elrond-wasm-debug]
version = "0.29.3"
